/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VehicleId = IDL.Nat;
export const DamageReportInput = IDL.Record({
  'locationDescription' : IDL.Text,
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
  'damageType' : IDL.Text,
  'severity' : IDL.Text,
  'vehicleId' : VehicleId,
});
export const DamageId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DamageReport = IDL.Record({
  'id' : DamageId,
  'status' : IDL.Text,
  'lastUpdate' : Time,
  'locationDescription' : IDL.Text,
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
  'reportDate' : Time,
  'reportedBy' : IDL.Principal,
  'damageType' : IDL.Text,
  'severity' : IDL.Text,
  'vehicleId' : VehicleId,
});
export const Vehicle = IDL.Record({
  'vehicleType' : IDL.Text,
  'vehicleNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDamageReport' : IDL.Func([DamageReportInput], [DamageId], []),
  'addPhotoToDamageReport' : IDL.Func([DamageId, IDL.Text], [], []),
  'addVehicle' : IDL.Func([IDL.Text, IDL.Text], [VehicleId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDamageReports' : IDL.Func([], [IDL.Vec(DamageReport)], ['query']),
  'getAllDamagesForVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Vec(DamageReport)],
      ['query'],
    ),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getAvailableVehicles' : IDL.Func([IDL.Text], [IDL.Vec(Vehicle)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOpenDamages' : IDL.Func([], [IDL.Vec(DamageReport)], ['query']),
  'getReportsByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DamageReport)],
      ['query'],
    ),
  'getReportsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DamageReport)],
      ['query'],
    ),
  'getReportsForVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Vec(DamageReport)],
      ['query'],
    ),
  'getVehicleById' : IDL.Func([VehicleId], [Vehicle], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeVehicle' : IDL.Func([VehicleId], [], []),
  'updateDamageReportStatus' : IDL.Func([DamageId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VehicleId = IDL.Nat;
  const DamageReportInput = IDL.Record({
    'locationDescription' : IDL.Text,
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
    'damageType' : IDL.Text,
    'severity' : IDL.Text,
    'vehicleId' : VehicleId,
  });
  const DamageId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DamageReport = IDL.Record({
    'id' : DamageId,
    'status' : IDL.Text,
    'lastUpdate' : Time,
    'locationDescription' : IDL.Text,
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
    'reportDate' : Time,
    'reportedBy' : IDL.Principal,
    'damageType' : IDL.Text,
    'severity' : IDL.Text,
    'vehicleId' : VehicleId,
  });
  const Vehicle = IDL.Record({
    'vehicleType' : IDL.Text,
    'vehicleNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDamageReport' : IDL.Func([DamageReportInput], [DamageId], []),
    'addPhotoToDamageReport' : IDL.Func([DamageId, IDL.Text], [], []),
    'addVehicle' : IDL.Func([IDL.Text, IDL.Text], [VehicleId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDamageReports' : IDL.Func([], [IDL.Vec(DamageReport)], ['query']),
    'getAllDamagesForVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Vec(DamageReport)],
        ['query'],
      ),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getAvailableVehicles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOpenDamages' : IDL.Func([], [IDL.Vec(DamageReport)], ['query']),
    'getReportsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DamageReport)],
        ['query'],
      ),
    'getReportsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DamageReport)],
        ['query'],
      ),
    'getReportsForVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Vec(DamageReport)],
        ['query'],
      ),
    'getVehicleById' : IDL.Func([VehicleId], [Vehicle], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeVehicle' : IDL.Func([VehicleId], [], []),
    'updateDamageReportStatus' : IDL.Func([DamageId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };