/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DamageId = bigint;
export interface DamageReport {
  'id' : DamageId,
  'status' : string,
  'lastUpdate' : Time,
  'locationDescription' : string,
  'description' : string,
  'photoIds' : Array<string>,
  'reportDate' : Time,
  'reportedBy' : Principal,
  'damageType' : string,
  'severity' : string,
  'vehicleId' : VehicleId,
}
export interface DamageReportInput {
  'locationDescription' : string,
  'description' : string,
  'photoIds' : Array<string>,
  'damageType' : string,
  'severity' : string,
  'vehicleId' : VehicleId,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle { 'vehicleType' : string, 'vehicleNumber' : string }
export type VehicleId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDamageReport' : ActorMethod<[DamageReportInput], DamageId>,
  'addPhotoToDamageReport' : ActorMethod<[DamageId, string], undefined>,
  'addVehicle' : ActorMethod<[string, string], VehicleId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDamageReports' : ActorMethod<[], Array<DamageReport>>,
  'getAllDamagesForVehicle' : ActorMethod<[VehicleId], Array<DamageReport>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getAvailableVehicles' : ActorMethod<[string], Array<Vehicle>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOpenDamages' : ActorMethod<[], Array<DamageReport>>,
  'getReportsByStatus' : ActorMethod<[string], Array<DamageReport>>,
  'getReportsByUser' : ActorMethod<[Principal], Array<DamageReport>>,
  'getReportsForVehicle' : ActorMethod<[VehicleId], Array<DamageReport>>,
  'getVehicleById' : ActorMethod<[VehicleId], Vehicle>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeVehicle' : ActorMethod<[VehicleId], undefined>,
  'updateDamageReportStatus' : ActorMethod<[DamageId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];